### ISSUE TITLE
[Project Proposal Review] Evaluating the Software Carbon Intensity of Foundation Models

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards_wg#4]
**Standards Working Group Project Proposal Review** - Evaluating the Software Carbon Intensity of Foundation Models -Dr. Ziliang Zong (Texas State University)

**Review dates 03 Feb - 10th Feb (1630 GMT)**

**Comment Submissions ** - All comments to be submitted directly against the [project proposal document](https://docs.google.com/document/d/16bcRAyN9ZxVKNf1GkaIbDJXnxvIo7Goe/edit)
Note: No comments can be submitted after the review has closed

**Scope** - Foundation models (e.g. BERT and BET-3) refer to large scale AI models that are trained on massive amount of data and can be adapted to a wide range of tasks (e.g. language, vision, human interaction etc.). Although foundation models are very powerful, they are extremely resource hungry with significant carbon emissions because of their scale. This project aims to create a comprehensive case study on evaluating the impact of foundation AI models on environment by applying the Software Carbon Intensity (SCI) specification.

**Comment by atg-abhishek** [comment]
Project has been approved by the WG during the call.
